[package]
name = "bevy_game_multiplayer"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[features]
default = ["direct"]
direct = [
    "dep:aeronet_webtransport",
    "dep:x509-parser",
]
test-harness = []

[dependencies]
aeronet = { version = "=0.21.0", default-features = false, features = ["std"] }
aeronet_replicon = { version = "=0.21.0", default-features = false, features = ["std", "client", "server"] }
aeronet_webtransport = { version = "=0.21.0", default-features = false, features = ["client", "server", "self-signed"], optional = true }
atomicwrites = "0.4.4"
base64 = "0.22"
bevy.workspace = true
bevy_replicon = { version = "=0.41.1", default-features = false, features = ["client", "server"] }
if-addrs.workspace = true
rand = "0.8"
serde.workspace = true
serde_json = "1"
sha2 = "0.10"
x509-parser = { version = "=0.17.0", optional = true }

[dev-dependencies]
rcgen = "=0.13.2"
tempfile = "3"

[lints]
workspace = true
