[package]
name = "bevy_game_discovery"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[features]
default = []
mdns = ["dep:dns-sd-native", "dep:mdns-sd-discovery", "dep:tokio", "dep:if-addrs"]
tailscale-cli = ["dep:tokio", "tokio/process", "tokio/io-util"]

[dependencies]
base64 = "0.22"
bevy.workspace = true
bevy_game_session.workspace = true
if-addrs = { workspace = true, optional = true }
dns-sd-native = { version = "=0.1.1", optional = true }
mdns-sd-discovery = { version = "=0.3.0", optional = true }
serde.workspace = true
serde_json = "1"
tokio = { workspace = true, optional = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
